In [1]:
import pandas as pd
import re
from   lib.etl import SpreadSheet
from   sqlalchemy import create_engine

In [2]:
def connect_sql_engine(user, password, host='postgres', port=5432, database='db'):
    return create_engine(f"postgresql://{user}:{password}@{host}:{str(port)}/{database}")

sql_engine = connect_sql_engine(
    "admin",
    "admin"
)

In [3]:
sales = SpreadSheet({
    "fpath": "./assets/sales/ยอดขาย 01_2025.1.xlsx",
    "head_offset": 1,
    "head_cut": 1,
    "tail_cut": 3
}).read()

sales.get_df()

,ประเภท,รายการ,สร้างโดย,ชื่อลูกค้า,รหัสลูกค้า,อีเมลลูกค้า,เบอร์โทรศัพท์ลูกค้า,ที่อยู่ลูกค้า,เลขผู้เสียภาษี,ชื่อตัวแทน,...,จำนวนเงินที่ชำระ,วันที่ชำระเงิน,รหัสสินค้า,ชื่อสินค้า,จำนวน,ราคาต่อหน่วย,ส่วนลดต่อหน่วย,ราคารวม,ล็อต,หมวดหมู่
0,ขายออก,250116K679CFP9,NaN,ณ******ฐ,NaN,NaN,******58,******องแขม แขวงหนองค้างพลู กรุงเทพ 10160 แขวง...,NaN,NaN,...,NaN,16/1/2025 21:39,TTP-011-XL,Toogtons boxer ชาย/หญิง Collection Monochrome ...,1.0,NaN,NaN,NaN,NaN,Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...
1,ขายออก,250116K679CFP9,NaN,ณ******ฐ,NaN,NaN,******58,******องแขม แขวงหนองค้างพลู กรุงเทพ 10160 แขวง...,NaN,NaN,...,NaN,NaN,TTP-011-XXL,Toogtons boxer ชาย/หญิง Collection Monochrome ...,4.0,NaN,NaN,NaN,NaN,Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...
2,ขายออก,250115J1GQ5MCW,NaN,น******ง,NaN,NaN,******57,****** ต.ป่าสัก ตำบลป่าสัก อำเภอเมืองลำพูน จัง...,NaN,NaN,...,NaN,16/1/2025 12:38,TTG107-L,Toogtons boxer ชาย/หญิง Collection Space ทุกตอ...,1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
3,ขายออก,250115J1GQ5MCW,NaN,น******ง,NaN,NaN,******57,****** ต.ป่าสัก ตำบลป่าสัก อำเภอเมืองลำพูน จัง...,NaN,NaN,...,NaN,NaN,TTF105-L,Toogtons boxer ชาย/หญิง Collection ผักผลไม้ ทุ...,1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
4,ขายออก,250115JVG61DY6,NaN,น******ง,NaN,NaN,******22,******9/28-29 ม.17 ต.คลองหนึ่ง ตำบลคลองหนึ่ง อ...,NaN,NaN,...,NaN,16/1/2025 11:46,TTF111-3XL,Toogtons boxer ชาย/หญิง Collection Food ทุกตอน...,1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23035,ขายออก,IV-TT-2024121121,เจน (Sale online),ธนากร อนุจิตร,NaN,NaN,0919787049,16/44 หมู่บ้านเศรษฐพงศ์ หมู่ที่ 4 ซอย7 ถนนบางค...,NaN,NaN,...,NaN,NaN,TTA155-XXL,(D2) หมาปั๊ก Ash Brown (ผ้านุ่ม)(XXL),1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
23036,ขายออก,IV-TT-2024121121,เจน (Sale online),ธนากร อนุจิตร,NaN,NaN,0919787049,16/44 หมู่บ้านเศรษฐพงศ์ หมู่ที่ 4 ซอย7 ถนนบางค...,NaN,NaN,...,NaN,NaN,TTA154-XXL,บลูด็อก พื้นเทา (ผ้านุ่ม)(XXL),1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
23037,ขายออก,IV-TT-2024121121,เจน (Sale online),ธนากร อนุจิตร,NaN,NaN,0919787049,16/44 หมู่บ้านเศรษฐพงศ์ หมู่ที่ 4 ซอย7 ถนนบางค...,NaN,NaN,...,NaN,NaN,TTG135-XXL,(D4) Christmas กวางเรนเดียร์ -reindeer (ผ้านุ่...,1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
23038,ขายออก,IV-TT-2024121121,เจน (Sale online),ธนากร อนุจิตร,NaN,NaN,0919787049,16/44 หมู่บ้านเศรษฐพงศ์ หมู่ที่ 4 ซอย7 ถนนบางค...,NaN,NaN,...,NaN,NaN,TTG133-XXL,(D4) แมงกระพรุน -Jellyfish (ผ้านุ่ม)(XXL),1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...
23039,ขายออก,IV-TT-2024121121,เจน (Sale online),ธนากร อนุจิตร,NaN,NaN,0919787049,16/44 หมู่บ้านเศรษฐพงศ์ หมู่ที่ 4 ซอย7 ถนนบางค...,NaN,NaN,...,NaN,NaN,TTG132-XXL,(D4) วาฬ -Whale (ผ้านุ่ม) (XXL),1.0,NaN,NaN,NaN,NaN,Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...

In [4]:
def rename_entry (df):
    df.rename(
        columns = {
            'วันที่ทำรายการ': 'transaction_date',
            'รหัสสินค้า': 'item_id',
            'ช่องทางการขาย': 'platform',
            'จำนวน': 'quantity'
        },
        inplace = True
    )
    return df

def reformat_date (df):
    df['transaction_date'] = pd.to_datetime(
        df['transaction_date'],
        format="%d/%m/%Y"
    )
    return df

filtered = sales.extract_columns([
    'วันที่ทำรายการ',
    'รหัสสินค้า',
    'ช่องทางการขาย',
    'จำนวน'
]).df_opr(lambda df: df.sort_values(
    by='วันที่ทำรายการ', ascending=True, ignore_index=True
)).df_opr(rename_entry).df_opr(reformat_date)

# filtered.export_sql(sql_engine, "sales")
filtered.export_csv(f"./processed/{filtered.fname}.csv").get_df()

      transaction_date      item_id        platform  quantity
0           2025-01-01  TTP-011-XXL          Shopee       6.0
1           2025-01-01   TTG107-XXL  TIKTOK TOOGTON       1.0
2           2025-01-01     TTG141-L  TIKTOK TOOGTON       1.0
3           2025-01-01     TTG135-L  TIKTOK TOOGTON       1.0
4           2025-01-01     TTG107-M  TIKTOK TOOGTON       1.0
...                ...          ...             ...       ...
23035       2025-01-09  TTP-010-3XL        Facebook       2.0
23036       2025-01-09  TTP-007-3XL        Facebook       2.0
23037       2025-01-09  TTP-013-3XL        Facebook       2.0
23038       2025-01-09  TTP-040-3XL        Facebook       1.0
23039       2025-01-09  TTP-013-3XL  TIKTOK TOOGTON       1.0

[23040 rows x 4 columns]

In [5]:
skus = SpreadSheet({
    "fpath": "./assets/skus/หมวดหมู่สินค้า.xlsx",
    "head_offset": 1,
    "head_cut": 1,
    "tail_cut": 3,
}).read()

skus.get_df()

,รหัสสินค้า,ชื่อสินค้า,หมวดหมู่,หมวดหมู่ย่อย,หน่วยสินค้า,Barcode
0,TTLS198-XL,น้องโซบะ ขายาว(XL),กางเกงขายาว,NaN,ชิ้น,TTLS198-XL
1,TTLS198-L,น้องโซบะ ขายาว(L),กางเกงขายาว,NaN,ชิ้น,TTLS198-L
2,TTLS198-M,น้องโซบะ ขายาว(M),กางเกงขายาว,NaN,ชิ้น,TTLS198-M
3,TTLS197-XL,น้องมิก้า ขายาว(XL),กางเกงขายาว,NaN,ชิ้น,TTLS197-XL
4,TTLS197-L,น้องมิก้า ขายาว(L),กางเกงขายาว,NaN,ชิ้น,TTLS197-L
...,...,...,...,...,...,...
5204,TTA77-M,(A2) แมวชูนิ้วกลางพื้นฟ้า - middle finger cat(M),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,ชิ้น,TTA77-M
5205,TTA83-XXL,(D2) หมาลายจุดพื้นแดง - polka dot(M)(XXL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,ชิ้น,TTA83-XXL
5206,TTA83-XL,(C2) หมาลายจุดพื้นแดง - polka dot(XL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,ชิ้น,TTA83-XL
5207,TTA83-L,(B2) หมาลายจุดพื้นแดง - polka dot(M)(L),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,ชิ้น,TTA83-L
5208,TTA83-M,(A2) หมาลายจุดพื้นแดง - polka dot(M),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,ชิ้น,TTA83-M

In [6]:
def normalize_head (df):
    df.rename(
        columns = {
            'ชื่อสินค้า': 'name',
            'รหัสสินค้า': 'raw_id',
            'หมวดหมู่': 'category',
            'หมวดหมู่ย่อย': 'subcategory',
            'หน่วยสินค้า': 'unit',
        },
        inplace = True,
    )
    return df

def normalize_body (df):
    df['unit'] = (
        df['unit']
        .astype(str)
        .str.replace('ชิ้น', 'piece', regex=False)
        .str.replace('เซต', 'set', regex=False)
        .str.replace('ตัว', 'one-unit', regex=False)
        .str.replace('แพ็ค', 'pack', regex=False)
        .str.replace('คู่', 'pairs', regex=False)
        .str.replace('ม้วน', 'roll', regex=False)
        .str.replace('กล่อง', 'box', regex=False)
        .str.replace('รายการ', 'order', regex=False)
        .str.replace('ก้อน', 'cell/lump', regex=False)
        .str.replace('กิโล', 'kg', regex=False)
        .str.replace('แท่ง', 'piece/stick', regex=False)
    )
    df['size'] = (
        df['size']
        .astype(str)
        .str.replace('แบบหนา', 'thick', regex=False)
        .str.replace('แบบบาง', 'thin', regex=False)
        .str.replace('นิ้ว', 'inchs', regex=False)
    )
    return df

def separate(row):
    raw_id = str(row["raw_id"])
    parts = raw_id.rsplit("-", 1)   # split from the right, at most once

    white_lst = ["M", "L", "XL", "XXL", "3XL", "Free size"]
    black_lst = ["TTB", "OF", "WH"]

    row["size"] = None
    if len(parts) == 2 and parts[1] in white_lst:
        row["size"] = parts[1]
        return row
    if len(parts) < 2 or parts[0] in black_lst:
        return row
    # Try extracting from name (last parenthesis group)
    matches = re.findall(r"\((.*?)\)", str(row["name"]))
    if matches:
        row["size"] = matches[-1]   # last match
    return row

filtered = skus.extract_columns([
    'รหัสสินค้า',
    'ชื่อสินค้า',
    'หมวดหมู่',
    'หมวดหมู่ย่อย',
    'หน่วยสินค้า'
])\
.df_opr(lambda df: df.sort_values(by='ชื่อสินค้า', ascending=True, ignore_index=True))\
.df_opr(normalize_head)\
.df_opr(lambda df: df.apply(separate, axis=1))\
.df_opr(normalize_body)

# filtered.export_sql(sql_engine, "skus")
filtered.export_csv(f"./processed/{filtered.fname}.csv").get_df()

,raw_id,name,category,subcategory,unit,size
0,TT-CVC-XL,"CVC (Poly 60% , Cotton 40%)(XL)",NaN,NaN,one-unit,XL
1,Sock-A1,Sock Thick Woven (แบบหนา),คอลเลคชั่นลิมิเตด / Limited Collection,NaN,piece,thick
2,SWTT02-Free size,Sweater - (ซานตาคลอสพื้นครีม)(Free size),Sweater,NaN,one-unit,Free size
3,SWTT03-Free size,Sweater - (ต้นคริสต์มาสพื้นเขียว)(Free size),Sweater,NaN,one-unit,Free size
4,Sock-B1,Thick Woven (แบบบาง),คอลเลคชั่นลิมิเตด / Limited Collection,NaN,piece,thin
...,...,...,...,...,...,...
5204,TTLS176-XL,ไอศครีม ขายาว(XL),กางเกงขายาว,NaN,piece,XL
5205,TTG146-L,ไอศครีม(L),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,piece,L
5206,TTG146-M,ไอศครีม(M),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,piece,M
5207,TTG146-XL,ไอศครีม(XL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,piece,XL
5208,TTG146-XXL,ไอศครีม(XXL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,NaN,piece,XXL

In [7]:
stocks = SpreadSheet({
    "fpath": "./assets/stocks/สินค้า 7.xlsx",
    "head_offset": 1,
    "head_cut": 1,
    "tail_cut": 3,
}).read()

stocks.get_df()

,รหัส,สินค้า,หมวดหมู่,จำนวน
0,A171-L,"(B1)ไก่พื้นดำ/Chicken, black background(L)",Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...,0.0
1,A171-M,"(A1)ไก่พื้นดำ/Chicken, black background(M)",Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...,0.0
2,A171-XL,"(C1)ไก่พื้นดำ/Chicken, black background(XL)",Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...,0.0
3,A171-XXL,"(D1)ไก่พื้นดำ/Chicken, black background(XXL)",Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...,0.0
4,A172-L,"(B1)นีโม่พื้นดำ/Nemo,black background(L)",Boxer Short Basic Plain (ผ้ายืด ทั่วไปและสีพื...,0.0
...,...,...,...,...
4962,TTLS148-L,แมวส้มพื้นครีม ขายาว (ผ้านุ่ม) New(L),กางเกงขายาว,1234.0
4963,TTLS159-L,โดนัทชมพูเล็ก ขายาว (ผ้านุ่ม) - donut(L),กางเกงขายาว,978.0
4964,TTLS160-L,อาโวคาโด้เล็กพื้นเขียวเข้ม ขายาว (ผ้านุ่ม) - a...,กางเกงขายาว,1145.0
4965,TTG137-L,(B4) ชินจังนั่งเล่นกับชิโระ(L),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,1434.0
4966,TTG139-L,(B4) ชินจังใส่ชุดกิมโมโน(L),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,2323.0

In [8]:
def normalize_head (df):
    df.rename(
        columns = {
            'รหัส': 'raw_id',
            'สินค้า': 'name',
            'หมวดหมู่': 'category',
            'จำนวน': 'quantity'
        },
        inplace = True,
    )
    return df

filtered = stocks.extract_columns([
    'รหัส',
    'สินค้า',
    'หมวดหมู่',
    'จำนวน'
])\
.df_opr(lambda df: df.sort_values(by='สินค้า', ascending=True, ignore_index=True))\
.df_opr(normalize_head)

# filtered.export_sql(sql_engine, "stock")
filtered.export_csv(f"./processed/{filtered.fname}.csv").get_df()

,raw_id,name,category,quantity
0,SWTT02-Free size,Sweater - (ซานตาคลอสพื้นครีม)(Free size),Sweater,0.0
1,SWTT03-Free size,Sweater - (ต้นคริสต์มาสพื้นเขียว)(Free size),Sweater,0.0
2,TTB-11-XL,ป้ายราคา 120 บาท (แบบที่ 1)(XL),อุปกรณ์การขาย,0.0
3,TTB-11-3XL,ป้ายราคา 140 บาท (แบบที่ 1)(3XL),อุปกรณ์การขาย,0.0
4,TTS24-M,ผ้าเชิ้ต-ดำล้วน (ทรงเก่า)(M),Boxer ทรงเกาหลี (ผ้าเชิ้ต),0.0
...,...,...,...,...
4962,TTLS176-XL,ไอศครีม ขายาว(XL),กางเกงขายาว,0.0
4963,TTG146-L,ไอศครีม(L),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,3.0
4964,TTG146-M,ไอศครีม(M),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,1.0
4965,TTG146-XL,ไอศครีม(XL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Si...,4.0
4966,TTG146-XXL,ไอศครีม(XXL),Boxer Short Printed Fabric (ผ้ายืดพิมพ์ลาย Siz...,2.0